// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Alfan Hidayat';
export const SITE_DESCRIPTION = 'Welcome to my website!';
export const HOME_TITLE = 'Home | Alfan'
export const BLOG_TITLE = 'Blog | Alfan'
export const ABOUT_TITLE = 'About | Alfan'

export const HTML = 'HTML'
export const CSS = 'CSS'
export const JS = 'JavaScript'
export const REACT = 'REACT'
export const CPP = 'C++'
export const ASTRO = 'ASTRO'

export const MYNAME = 'Alfan Hidayat'
export const INDEX_DESCRIPTION = 'Hello, Everyone! '
export const INDEX_DESCRIPTION_1 = 'I am a newbie front-end developer, and practicing to create a website and improve my frontend skills.'
export const INDEX_DESCRIPTION_2 = 'I am currently focused on becoming a skilled front-end developer with a passion for building engaging and user-friendly web applications.'
export const INDEX_DESCRIPTION_3 = 'I independently learned '
export const INDEX_DESCRIPTION_4 = ', and'
export const INDEX_DESCRIPTION_5 = ' at home, including exploring'
export const INDEX_DESCRIPTION_6 = ' Meanwhile, I focused on the '
export const INDEX_DESCRIPTION_7 = 'programming language at campus. With these dual approaches, I ve been developing  skills in both web and programming domains.'
export const INDEX_FEATURED = 'Featured Technologies Used'
export const INDEX_REFERENCES = 'References'
export const INDEX_SKILSS = 'My Skills'

export const ABOUT_EVERYONE = 'Hi, Everyone!'
export const ABOUT_WEBDEV = 'Alfan Hidayat | Web Developer'
export const ABOUT_DESCRIPTION = 'I am a student in the Informatics Engineering Study Program at Pamulang University. I am currently learning in the world of web development, especially in the field of front-end development.'
export const ABOUT_CONTACT = 'Contact me via'
export const MYINSTAGRAM = '@kelraskie'
export const MYEMAIL = 'alfanhidayat12321@gmail.com'
export const MYTHREAD = '@alpan'
export const ABOUT_CLICKIMAGE = 'You can contact me via email & instagram, or click image.'
export const ABOUT_THANKYOU = 'Thank Youu!👋‎‎'

export const BLOG_BLOG = 'alpan/blog'
export const BLOG_DESCRIPTION = 'I share my process, experiences, tips and resources related to web and mobile development, such as React and Javascript, in my blog to help others on their web development journey.'
export const BLOG_ABOUT = 'About Me?'
export const BLOG_MYPROJECT = 'My Project'
export const BLOG_FORMLOGIN = 'Form login'
export const FORMLOGIN_1 = 'Created a login form using '
export const FORMLOGIN_2 = ' and'
export const FORMLOGIN_3 = '. This project strengthened my understanding of web fundamentals, allowing for aesthetically pleasing designs without additional frameworks. A step towards independent web design and development skills.'
export const BLOG_PORTO = 'Website Portfolio'
export const PORTO_1 = 'I crafted a portfolio website using the '
export const PORTO_2 = ' framework'
export const BLOG_LINK = '//alpan.app/blog'
export const BLOG_VSCODE = 'VS Code'
export const BLOG_GITHUB = 'Github'
export const BLOG_GIT = 'Gitignore'